reminders = "Don't forget to format!"

[[tasks]]
name = "Clippy"
command = "cargo clippy -q"

[actions.f]
name = "Format"
command = "cargo fmt"

[actions.t]
name = "Test"
command = "cargo test -q"

[actions.b]
name = "Benchmark"
command = "cargo bench -q"
pause = true

[actions.R]
name = "Build release"
command = "cargo build --release"

[actions.r]
name = "Run"
command = "cargo run"

[actions.c]
name = "Clean"
command = "cargo clean"
